// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9_HaCOoXBISAe1uwbxY4xOshSYUERsqg',
    appId: '1:1077257027416:web:6ec779ea7755aa99b0ef2d',
    messagingSenderId: '1077257027416',
    projectId: 'pbandj-d614c',
    authDomain: 'pbandj-d614c.firebaseapp.com',
    storageBucket: 'pbandj-d614c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL6hWLz4Ird1eZxA9vuD7dWiOCEaurWjI',
    appId: '1:1077257027416:android:a57c89c4b4506cceb0ef2d',
    messagingSenderId: '1077257027416',
    projectId: 'pbandj-d614c',
    storageBucket: 'pbandj-d614c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9C_klAAm01ndiVS-ZT_uw2Gd-mqOmyO0',
    appId: '1:1077257027416:ios:50b45d2b6c9d8649b0ef2d',
    messagingSenderId: '1077257027416',
    projectId: 'pbandj-d614c',
    storageBucket: 'pbandj-d614c.appspot.com',
    iosClientId: '1077257027416-1m4dlcnkgbp65uagahelknt2q26pqft2.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9C_klAAm01ndiVS-ZT_uw2Gd-mqOmyO0',
    appId: '1:1077257027416:ios:50b45d2b6c9d8649b0ef2d',
    messagingSenderId: '1077257027416',
    projectId: 'pbandj-d614c',
    storageBucket: 'pbandj-d614c.appspot.com',
    iosClientId: '1077257027416-1m4dlcnkgbp65uagahelknt2q26pqft2.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
